name: Crate Release

on:
  push:
    tags:
      - 'crate-v*'

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Verify tag matches Cargo.toml version
        shell: bash
        run: |
          TAG_REF="${GITHUB_REF#refs/tags/}"
          TAG_VER="${TAG_REF#crate-v}"
          CARGO_VER=$(sed -n -E 's/^version = "([^"]+)"/\1/p' Cargo.toml | head -n1)
          echo "Tag version: $TAG_VER"
          echo "Cargo.toml version: $CARGO_VER"
          if [[ "$TAG_VER" != "$CARGO_VER" ]]; then
            echo "Error: tag version ($TAG_VER) does not match Cargo.toml version ($CARGO_VER)" >&2
            exit 1
          fi

      - name: Build and test
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Package (dry run)
        run: cargo package --verbose

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --verbose

